### ISSUE TITLE
파일명과 함수 및 클래스 이름 통일성

### ISSUE THREAD

**Issue by suinautant** [team-cjmp/react_instagram_clone_front#1]
https://github.com/team-cjmp/react_instagram_clone_front/blob/1d83802d91bd499d50d06f4a8db3e8981cd65abd/src/components/NavBar.jsx#L4

**Comment by suinautant** [comment]
본문 파일 이름 NavBar 내부 함수 Navbar
하나만 작성할 때는 이름 통일하는게 어떨까요?

**Comment by lulupang2** [comment]
수정완료
